# Generated by Django 4.1.3 on 2022-11-23 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2022, 11, 23, 6, 43, 29, 323059, tzinfo=datetime.timezone.utc), max_length=3, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
