# Generated by Django 4.1.3 on 2022-11-23 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2022, 11, 23, 9, 35, 48, 430014, tzinfo=datetime.timezone.utc), max_length=25, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
