# Generated by Django 4.1.3 on 2022-11-23 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2022, 11, 23, 9, 59, 57, 559111, tzinfo=datetime.timezone.utc), max_length=5, verbose_name='Код специальности'),
            preserve_default=False,
        ),
    ]
