# Generated by Django 4.1.3 on 2022-11-24 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.BooleanField(null=True, verbose_name='Наличие опыта'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 6, 10, 31, 832562, tzinfo=datetime.timezone.utc), max_length=10, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('', 'Выбери характеристики'), ('Открытый', 'Открытый'), ('Экстраверт', 'Экстраверт'), ('Интроверт', 'Интроверт'), ('Сдержанный', 'Сдержанный'), ('Серьезный', 'Серьезный')], max_length=50, null=True, verbose_name='Личностные характеристики'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 6, 11, 6, 415565, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Вилка зарплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('1', 'Да'), ('0', 'Нет')], default='', max_length=10, verbose_name='Курит'),
        ),
    ]
