# Generated by Django 4.1.3 on 2022-11-24 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_experience_candidate_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=datetime.datetime(2022, 11, 24, 11, 8, 1, 473119, tzinfo=datetime.timezone.utc), upload_to='', verbose_name='Резюме'),
            preserve_default=False,
        ),
    ]
