# Generated by Django 4.1.3 on 2022-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_candidate_databases_alter_candidate_frameworks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True, verbose_name='Заметки согласования'),
        ),
    ]
